
project_id = "kztelbnarzrpbjlqastg"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54320
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
refresh_token_reuse_interval = 10
enable_signup = true
enable_confirmations = false

[functions.encrypt-certificate]
verify_jwt = true

[functions.migrate-certificates]
verify_jwt = false

[functions.verifactu]
verify_jwt = true

[functions.change-superuser-password]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.list-users]
verify_jwt = false

[functions.prestashop-sync-stock]
verify_jwt = true

[functions.prestashop-test-connection]
verify_jwt = true

[functions.process-pdf-invoice]
verify_jwt = true

[functions.send-document-email]
verify_jwt = true

[functions.send-test-email]
verify_jwt = true

[functions.superuser-auth]
verify_jwt = false
